-- MySQL Script generated by MySQL Workbench
-- Tue Dec  2 07:52:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rapidoEseguro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rapidoEseguro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rapidoEseguro` DEFAULT CHARACTER SET utf8 ;
USE `rapidoEseguro` ;

-- -----------------------------------------------------
-- Table `rapidoEseguro`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapidoEseguro`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `data_cad` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_nasc` DATE NOT NULL,
  `idade` INT NOT NULL,
  `status_cliente` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapidoEseguro`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapidoEseguro`.`telefones` (
  `id_telefone` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(12) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_telefone`, `id_cliente`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE,
  INDEX `fk_telefones_clientes_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_telefones_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `rapidoEseguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapidoEseguro`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapidoEseguro`.`enderecos` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `complemento` VARCHAR(150) NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `id_cliente` INT NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_endereco`, `id_cliente`),
  INDEX `fk_enderecos_clientes1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_clientes`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `rapidoEseguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapidoEseguro`.`tipo_entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapidoEseguro`.`tipo_entrega` (
  `id_tipo_entrega` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_tipo_entrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapidoEseguro`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapidoEseguro`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `data_pedido` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `distancia` DECIMAL(12,2) NOT NULL,
  `peso_carga` DECIMAL(10,2) NOT NULL,
  `valor_km` DECIMAL(10,2) NOT NULL,
  `valor_kg` DECIMAL(10,2) NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_tipo_entrega` INT NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_cliente`, `id_tipo_entrega`),
  INDEX `fk_pedidos_clientes1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_pedidos_tipo_entrega1_idx` (`id_tipo_entrega` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `rapidoEseguro`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_tipo_entrega1`
    FOREIGN KEY (`id_tipo_entrega`)
    REFERENCES `rapidoEseguro`.`tipo_entrega` (`id_tipo_entrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapidoEseguro`.`status_entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapidoEseguro`.`status_entrega` (
  `id_status_entrega` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_status_entrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapidoEseguro`.`entregas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapidoEseguro`.`entregas` (
  `id_entregas` INT NOT NULL AUTO_INCREMENT,
  `valor_distancia` DECIMAL(10,2) NOT NULL,
  `valor_peso` DECIMAL(10,2) NOT NULL,
  `acrescimo` DECIMAL(10,2) NOT NULL,
  `desconto` DECIMAL(10,2) NOT NULL,
  `taxa_extra` DECIMAL(10,2) NOT NULL,
  `valor_final` DECIMAL(10,2) NOT NULL,
  `id_pedido` INT NOT NULL,
  `id_status_entrega` INT NOT NULL,
  PRIMARY KEY (`id_entregas`, `id_pedido`, `id_status_entrega`),
  INDEX `fk_entregas_pedidos1_idx` (`id_pedido` ASC) VISIBLE,
  INDEX `fk_entregas_status_entrega1_idx` (`id_status_entrega` ASC) VISIBLE,
  CONSTRAINT `fk_entregas_pedidos1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `rapidoEseguro`.`pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entregas_status_entrega1`
    FOREIGN KEY (`id_status_entrega`)
    REFERENCES `rapidoEseguro`.`status_entrega` (`id_status_entrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rapidoEseguro`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rapidoEseguro`.`estoque` (
  `id_estoque` INT NOT NULL,
  `descricao` VARCHAR(15) NOT NULL,
  `data_movimentacao` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_estoque`, `id_pedido`),
  INDEX `fk_estoque_pedidos1_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_pedidos1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `rapidoEseguro`.`pedidos` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
